### ISSUE TITLE
Legal Notice Page

### ISSUE THREAD

**Issue by mastizada** [itucsdb1630/itucsdb1630#25]

**Comment by bilginsed** [comment]
Page uploaded

**Comment by mastizada** [comment]
Pull request yollamadan issue-lari kapatmak dogru degil. Pull request-e resolve #issue-numarasi yazarsan otomatik olarak kapatir.

**Comment by mastizada** [comment]
@bilginsed  Sitenin Yasal Uyarı (Legal Notice) yazısı başka bir şirketle tam aynı olamaz. Bu nedenle yanlış bilgilerin acilen kaldırılması gerekiyor. Eğer sorun olursa bu işi başka birine vere biliriz.

**Comment by bilginsed** [comment]
İçeriği boşalttım. Daha sonra gerekli içeriği ekleyeceğim..
