### ISSUE TITLE
Movie DB design and Integration

### ISSUE THREAD

**Issue by emreeroglu** [itucsdb1630/itucsdb1630#37]

**Comment by mastizada** [comment]
models/user.py-da ornek obje var, filter, get, save, delete komutlarinin benzer olmasi onemli (aldiklari verilerin, parametrelerin ayni olmasi gerekiyor).

**Comment by mastizada** [comment]
@MemduhG , sende bir tek view.py kalmisti, onu da ekle, bu da hazir olsun
