### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by emreeroglu** [itucsdb1630/itucsdb1630#41]
User feedback form design and crud operations for it.

**Comment by mastizada** [comment]
contactus tablosu olucak, icinde id, title (baslik), content (soru metni), email, phone (telefon numarasi) gibi bilgiler olucak. Daha sonrasi icin daha genis bilgiler dusune biliriz ve ya kendin ekleye bilirsin, simdilik bunlar yeterli gibi.
